### ISSUE TITLE
Circle-Map takes longer on server

### ISSUE THREAD

**Issue by ABDULHZAU** [iprada/Circle-Map#18]
I have submitted my two bash jobs of Circle-Map to the server with 16 and 8 cpu's but still it has not finished. Please tell me whats wrong with it?
`JOBID     USER     STAT   QUEUE       FROM_HOST    EXEC_HOST    JOB_NAME    SUBMIT_TIME

35484    skabdul RUN     normal     mn02         16*c02n08   *rcle-Map1    Jul 19 09:46

31157     skabdul RUN     normal       mn02         8*c05n03     Circle-Map   Jul 18 15:28`

My pipeline is : 

`Circle-Map Realign -t 16 -i sort_circular_read_candidates.bam -qbam qname_M1_map.bam -sbam sorted_M1_map.bam -fasta Zea_mays.AGPv4.dna.toplevel.fa -o outcircle/my_circle_DNA.bed`

**Comment by iprada** [comment]
Dear Abdul,

Thanks for using Circle-Map. It is very hard to say why is Circle-Map run time so long if you do not provide more information. In order to help you with that I will need some information about it:

**Regarding software architecture:**

- How much RAM are you using in the jobs?


**Regarding your specific job:**

- How long has it been running?
- How big is your dataset?


** Regarding your dataset:**

- Is the dataset a circular DNA enriched dataset? Or is it a a regular WGS dataset?
- Was the DNA amplified? and how?


As general rule for the run time of Circle-Map, I regularly analyze datasets of 50-60 million of raw reads using the workflow described on the tutorial. The runtime of Circle-Map Realign  using 16 threads takes less than or around 1h of wall time. Regarding more corner cases, I have succesfully analyze  datasets of 1000-2000 million of single cell WGS datasets in around 6-10h using 16 threads.

On the circular DNA enriched data, I have experienced some corner cases were the run time was very long (around 30h). This was caused on heavily amplified datasets containg more than 700  million reads. The problem was caused due to exponential amplification of the input DNA .This caused that some regions of the genome had a very high sequencing coverage, causing the software to get stuck on those regions for a while.

I hope this information helps as a guide, and l am looking forward to hear back from you so that I can help you.

Best regards,

Inigo

**Comment by ABDULHZAU** [comment]
Hi,
Thanks for your detailed answer, actually now I have got the result after four days, but i would like to provide the details about my datasets;
 I have circular DNA enriched 254 million reads datasets.
I have amplified using the random rolling circle amplification reagent. .
My one another question is, how can I get the sequence data of each circular DNA result given by Circle-Map?, this is my important question please let me know about it.

**Comment by iprada** [comment]
Dear Abdul,

I am to hear Circle-Map worked for you. Regarding you questions:

*how can I get the sequence data of each circular DNA result given by Circle-Map?*

-If you are planning to get the reference sequence, give a look at `samtools faidx`.
-If you are planning to get the sequencing reads give a look at  `samtools view` and provide a genomic region.

* I have got almost more than 30,000 circular DNAs from my enriched circular data, do you think the result is reliable?*

This one is very hard to answer without knowing more. I regularly obtain reliable results that are then validadated by my colaborators in the lab. I created a guide with the output explanation that will help you on filtering the data. I suggest you read it and and apply the convenient filters based on that. Here is the link:

https://github.com/iprada/Circle-Map/wiki/Circle-Map-output-files

**Comment by ABDULHZAU** [comment]
[Circle-Map](https://github.com/iprada/Circle-Map/wiki/Circle-Map-output-files)
In column #5, note #2 says: 
-If you want to filter the output by read evidence, this is a good column to apply filters to as it provides a direct evidence of the amount of reads that cross the circular DNA breakpoint. In our experiments, we got reliable results applying a filter of at least 2 split reads. However, this is very dependent on the research question you want to answer. As a rule of thumb, we recommend setting a filter of 5-10 split reads if you want to minimize the number of false positives.

- My question is how to apply filter on it to give me the reads evidence for a circular DNA?

**Comment by iprada** [comment]
Just for the record. The answer to this thread was cross-posted in the thread #19
