### ISSUE TITLE
Realign process seems to freeze

### ISSUE THREAD

**Issue by tchrisboles** [iprada/Circle-Map#21]
After starting the Realign command, the terminal gives feedback (via progress bar) for about 15-20 minutes, and then freezes. The size of the temporary files also appears constant after this freeze occurs. The terminal view after the freeze looks like this:
![Circle-Map_freeze](https://user-images.githubusercontent.com/33500125/61999769-268f0180-b096-11e9-8834-816d2a9e80dd.PNG)

Is this normal behavior?

**Comment by tchrisboles** [comment]
Sorry, please disregard my earlier question. The program terminated after about 3 hours of processing. It wasn't frozen. 
Very interesting program. Thanks.

**Comment by iprada** [comment]
Dear tchrisboles,

Thank you very much for using Circle-Map and your kind words.

Regarding your issue, this is a known behaviour. It occurs because in the current implementation, the amount of work is not evenly distributed across worker threads. Hence, some threads are processing way more data than others. In the end, this causes that some threads (in your case a single thread) keep processing data while the rest of the threads have already finish.

I have a working prototype that mitigates this problem by distributing the work more evenly across the threads. Furthermore, this prototype is much faster, due to just-in-time compilation of the core python functions of the program using numba.

The new prototype version is in testing phase and I plan to release it within the next couple of weeks. I have reopen this issue, and I will leave like this until I manage to release the new version if it is fine for you.

Thanks for the feedback and feel free to open a new issue in case you encounter any problem. 

Best wishes,

Iñigo

**Comment by tchrisboles** [comment]
Ok I look forward to the new version with more equitable thread distribution. 

Do I close this issue or do you (I don't use github very often....?)?

**Comment by iprada** [comment]
Dear @tchrisboles,

Lets leave the issue open until I release the new version. As that would be the time when I have solve your specific issue.

Best,
Iñigo

**Comment by iprada** [comment]
Dear @tchrisboles,

I just released a new version of Circle-Map. The version v1.1.1 should address the problem you have observed. Furthermore, this version comes with a speed-up around 50%

To get the new version, you can install Circle-Map using pip or conda.

Best wishes,

Iñigo
