### ISSUE TITLE
Segmental duplications give false circle signals?

### ISSUE THREAD

**Issue by tchrisboles** [iprada/Circle-Map#22]
Inigo, 
I am developing sample prep application for mtDNA sequencing that should also be useful for ecDNA discovery. I lyse cells in the sample well of an electrophoresis cassette (SageHLS, Sage Science, Inc.) and run DNA into the gel under conditions where all genomic DNA becomes trapped in the wall of the sample well, and smaller DNA continues into the gel. The smaller DNA is purified by electroelution, and we sequence it on a Miseq. 

In our first experiment, we got a lot of mtDNA sequence that aligned at high quality. I ran Circle-Map on our data and sorted the bed file for high scoring circles using column 6. 
![20190729_top_circle_bed_entries](https://user-images.githubusercontent.com/33500125/62059758-d462f300-b1f1-11e9-8bd6-baa37d847ffe.PNG)

As expected, the mtDNA sequence stood out as the highest score (203000 in column 6) with very high numbers of discordant reads and split reads. 

However there was also one other high quality call on chr16. In further inspection, this potential circle would have been 11Mb in size (and included the centromere of chr16). I am doubtful that DNA of this size would enter our gel cassette. On inspection of the sequence boundaries, it appears that the right boundary turns out to be a segmental duplication of the left boundary. So it is a kind "false positive" signal, although it has the right general structure at the calculated joint to generate discordant reads and split reads that would be characteristic of a circular joint. As you pointed out in your tutorial, the poor coverage (0.82 uncovered sequence, column 11), would be a giveaway that something was not right. In my case, the size of the circle was also problematic, insofar as we were using a gel system of limited size capacity. 

I bring this up because I suspect the boundaries of segmental duplications may cause false "circle" signals for other users. I don't have any hot ideas for how to solve this, except perhaps to incorporate coverage data (column 11) in the circle score (column 6). 
![20190729_ends_high_scoring_11Mb_circle](https://user-images.githubusercontent.com/33500125/62060491-38d28200-b1f3-11e9-80a6-e676d56f909a.PNG)

Best regards, 
Chris

**Comment by iprada** [comment]
Dear Chris,

Thanks a lot for the your suggestion.  

This is usually a minor problem that keeps rolling around my head from time to time. As you have pointed out, the problem is caused by regions with homology, which cause that Circle-Map to output some erroneous calls. However, this erroneous identifications have always been a very small fraction of the datasets I have analyse, and the majority of the circles are always very well covered by sequencing ( Figure 2e in our preprint https://www.biorxiv.org/content/10.1101/654194v1.full).  If this is not your case, let me know and I will think about what could I do.

As you have suggest, a good way to get around this would be to incorporate the coverage information in the final circle score. That is actually a great idea, and I will definitely consider to change the scoring model to one that takes into account the genomic read coverage within the coordinates.

Thanks a lot for the feedback!

Best regards,

Iñigo

**Comment by tchrisboles** [comment]
You're very welcome. I look forward to using Circle-Map again later this
week (and to your future improvements).

Best regards,

Chris Boles, Ph.D, Chief Scientific Officer
Sage Science, Inc., 500 Cummings Center, Suite 2400, Beverly, MA 01915
Direct Office: +1-978-522-6284, Mobile: +1-781-856-2165
Company: +1-978-922-1832
chris.boles@sagescience.com

This e-mail may contain information that is confidential or privileged. If
you are not the intended recipient, do not read, copy or distribute the
e-mail or any attachments. Instead, please notify the sender and delete the
e-mail and any attachments. Thank you.
