### ISSUE TITLE
bwa not work

### ISSUE THREAD

**Issue by bossgaochuan** [iprada/Circle-Map#26]
Hi sir:
I meet a error
bwa mem -q hg38.fa unknown_circle_reads_1.fastq unknown_circle_reads_2.fastq > unknown_circle.sam
mem: invalid option -- 'q'

**Comment by iprada** [comment]
Dear boosgaochuan,

Thanks for using Circle-Map. This error is not part of the Circle-Map software. It is an error of bwa mem. Nevertheless, I think I can help you. The error occurs because you are using a old version of bwa. The last version of bwa (version: 0.7.17-r1188) includes the -q option. Hence, if you update bwa to the last version that step should work.

You can see the bwa version in your system by typing `bwa` in your terminal.

Let me me know if it works

Best,

Iñigo

**Comment by bossgaochuan** [comment]
Dear Iñigo,
It works well, thanks for your so fast response.

**Comment by iprada** [comment]
Glad to hear,

Have a happy circle hunt!

Best,

Iñigo
