### ISSUE TITLE
Realign process running at very low CPU Usage

### ISSUE THREAD

**Issue by huangyizR** [iprada/Circle-Map#27]
Thanks for providing this handy program for calling circular DNA.
I am running the Circle-Map Realign with a -t 40 option on the HPC. In the beginning, everything looks fine, the temp bed files keep updating and the CPU load is normal. However, to a certain point, the node became idle and the program only use very low CPU and the temp bed file was not updating. 

Till I write this issue, the program is still running. And the temp bed file stays the same size for around 10 hours. I wlll let you know if the program end up finished or failed. Thanks!

**Comment by iprada** [comment]
Dear Yizhou,

Thanks a lot for reporting the issue. Which version of Circle-Map are you using?

This used to be a problem on versions before the last version (v1.1.3). However, that problem was solved on the last release. If you are not using version v1.1.3, updating to the last version should solve your problem.

Best,

Inigo

**Comment by huangyizR** [comment]
Hi Inigo,
Thanks for your quick response! I did realize that there is a closed issue with a similar problem. I do use the version 1.1.3. 
I attach my code and output error of the process. This file pbs.circle_map.4.e662010.TXT, came from a finished Circle_Map realign process. There is some error: 

"RuntimeWarning: invalid value encountered in XXX "

This file :pbs.circle_map.6.e662009.TXT came from an unfinished and killed job. I saw some "[E::hts_open_format] Failed to open file sorted.bam" error that may be related to samtools. However, when I check those sorted.bam, it looks fine. 

I am trying to separate samtools and realign process now. In meaning time, It would be great if you can provide some advice about my problems. Thanks for your time! 

[pbs.circle_map.2.TXT](https://github.com/iprada/Circle-Map/files/4240497/pbs.circle_map.2.TXT)
[pbs.circle_map.4.e662010.TXT](https://github.com/iprada/Circle-Map/files/4240498/pbs.circle_map.4.e662010.TXT)
[pbs.circle_map.6.e662009.TXT](https://github.com/iprada/Circle-Map/files/4240499/pbs.circle_map.6.e662009.TXT)

**Comment by iprada** [comment]
Dear Yizhou,


Great to hear that v 1.1.3 is working for you.



Regarding pbs.circle_map.4.e662010.TXT:

The output messages looks fine. Those are not errors, they are some warnings raised by the software during coverage calculations on the circular DNA coordinates. In some cases you will get division by zero errors, and the software will raise a warning message. But the output of that job should be fine. I assume that you have some circular DNA calls, right?



Regarding the job pbs.circle_map.6.e662009.TXT:

I have sometimes observed this error due to the node getting out of temporary disk space. I suggest you to decrease the number of threads to 16 in order to reduce the temp disk usage and see what happens. At this moment this is a limitation on Circle-Map side and on the the long run I plan to solve and handle this probem. However this will require a lot of time to be production ready. 

If reducing the number of cores does not work, write me an email on this thread so that we can figure out a solution.

Best wishes,

Inigo

**Comment by huangyizR** [comment]
Dear Inigo,
Thanks for your detailed explanation.  I am running on 16 thread now to see if I have any luck. I will let you know how things going. 

Thanks!

Best,
Peter

**Comment by iprada** [comment]
I am closing the issue by now. Feel free to reopen if it did not work
