### ISSUE TITLE
Suspicious feedback during coverage computation

### ISSUE THREAD

**Issue by tchrisboles** [iprada/Circle-Map#31]
Is this normal? If not, what do I need to do to avoid this?

![Circle-Map invalid ulong_scalars](https://user-images.githubusercontent.com/33500125/76656309-af837c00-6545-11ea-862a-ae670b5ef9f9.PNG)

**Comment by iprada** [comment]
Dear Chris,

That is normal. Those warnings are caused due to some division by 0 errors. For example, if Circle-Map Realigns a soft-clipped read to a genomic region where there is no read-coverage, you will get this warnings as some of the metrics cannot be calculated. It should be safe to ignore them

Best wishes and stay safe,

Feel free to write if you have more questions

Iñigo

**Comment by tchrisboles** [comment]
Thanks!

Best regards, 

Chris Boles, Ph.D, Chief Scientific Officer 
Sage Science, Inc., 500 Cummings Center, Suite 2400, Beverly, MA 01915
Direct Office: +1-978-522-6284, Mobile: +1-781-856-2165
Company: +1-978-922-1832
chris.boles@sagescience.com

This e-mail may contain information that is confidential or privileged. If you are not the intended recipient, do not read, copy or distribute the e-mail or any attachments. Instead, please notify the sender and delete the e-mail and any attachments. Thank you.
