### ISSUE TITLE
AttributeError: 'int' object has no attribute 'is_integer'

### ISSUE THREAD

**Issue by poflawless** [iprada/Circle-Map#33]
When I run Circle-Map ReadExtractor in a conda environment use the following command:
 Circle-Map  ReadExtractor -i SRR6315400_q.bam -o SRR6315400_q_cir.bam 
there is something wrong occurred:
Traceback (most recent call last):
  File "/usr/local/bin/Circle-Map", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/circlemap/circle_map.py", line 1164, in main
    run = circle_map()
  File "/usr/local/lib/python2.7/dist-packages/circlemap/circle_map.py", line 130, in __init__
    object.extract_sv_circleReads()
  File "/usr/local/lib/python2.7/dist-packages/circlemap/extract_circle_SV_reads.py", line 115, in extract_sv_circleReads
    if (processed_reads/1000000).is_integer() == True:
AttributeError: 'int' object has no attriute 'is_integer'

I tried multiple methods, while it still didn't work out. Could you have any suggestions?

**Comment by iprada** [comment]
Dear @poflawless,

Thanks a lot for using Circle-Map and reporting the issue. Based on the traceback you reported, I think the issue is caused by the fact you are using python2.7. Circle-Map is implemented in >=python3.6, hence I will not support errors that occurred in python versions older than 3.6, as it is very likely that they are caused by backward compatibility issues.

I suggest the following:
 - Upgrade python to at least python3.6
 - Install Circle-Map on the new version of python
 - Hunt circles again with the new version of Circle-Map :)

Please, let me know if it works, and if feel free to open a new issue if you have any problem.

Best wishes,

Iñigo

**Comment by poflawless** [comment]
Dear @Iñigo,
Thank you for your suggestion. I have updated my python version to python3.6.5. And solved the issues I proposed before. Thank you again.

**Comment by iprada** [comment]
I am  very glad to hear that. Feel free to open a new issue if you have more questions

Best,

Inigo
